### ISSUE TITLE
Random IllegalStateException with getInstruments api

### ISSUE THREAD

**Issue by chedine** [zerodha/javakiteconnect#24]
I get a random and hard to reproduce **IllegalStateException** errors with calls to the api **GetInstruments**. Retrying the same , works. Exception trace below;

 java.lang.IllegalStateException: closed
 okio.RealBufferedSource.select(RealBufferedSource.kt:83)
 okhttp3.internal.Util.readBomAsCharset(Util.kt:256)
 okhttp3.ResponseBody.string(ResponseBody.kt:187)
 com.zerodhatech.kiteconnect.kitehttp.KiteResponseHandler.handle(KiteResponseHandler.java:34)
 at com.zerodhatech.kiteconnect.kitehttp.KiteRequestHandler.getCSVRequest(KiteRequestHandler.java:150)
 at com.zerodhatech.kiteconnect.KiteConnect.getInstruments(KiteConnect.java:651)

**Comment by kssujithcj** [comment]
Is this consistent or intermitent? How often do you fetch the instruments master dump?

**Comment by chedine** [comment]
> Is this consistent or intermitent? How often do you fetch the instruments master dump?

- Intermittent and I would say 10 to 15% of the times.
- I fetch instruments only once during the entire session (start to end).
